[programs.devnet]
solana_gif_portal = "8Ag4UkcLV5KLG3u1y2r5VUyJYGn1JoVzcDXv3JXVP3A9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ilyazub/.config/solana/id.json"

[scripts]
test = "node tests/solana_gif_portal.js"
